[package]
name = "ble-ingester"
version = "0.1.0"
edition = "2024"

[features]
default = ["mock"]
btleplug = ["dep:btleplug"]
mock = ["dep:rand"]

[dependencies]
btleplug = { version = "0.11.8", optional = true }
chrono = "0.4.42"
rand = { version = "0.9.2", optional = true }
serde = "1.0.228"
serde_yaml = "0.9.34"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "macros", "chrono", "sqlite"] }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-stream = "0.1.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "chrono"] }
uuid = "1.19.0"
